### PR TITLE
Use Vagrant plugins

### PR DESCRIPTION
**Pull request by mike182uk**
Hey,

This PR enables the project to make use of some Vagrant plugins that make things abit smoother to setup.

- [Vagrant Cachier](https://github.com/fgrehm/vagrant-cachier) - Caches downloaded packages. Speeds up re-provisioning and saves bandwidth.
- [Vagrant Hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) - Automatically updates hosts file on `vagrant up` and `vagrant destroy`. Removes manual step to be taken by user.
- [Vagrant Librarian Puppet](https://github.com/mhahn/vagrant-librarian-puppet) - Installs required puppet modules upon provisioning and automatically resolves module dependencies. Removes the need for submodules.

### CODE REVIEW

**Comment by cwonrails** [comment]
+1 - maintainers?

**Comment by cwonrails** [comment]
Actually @mike182uk does the Puppet 3 syntax (hasn't yet been updated to 4) lead to any breakage?

**Comment by mike182uk** [comment]
@cwonrails No breakages, everything works as it did before :smiley:

**Comment by ErisDS** [comment]
I keep trying to use our vagrant setup instead of having everything directly on my mac, and often seem to hit issues (yes, that's pretty vague). It already has quite a few setup steps, is installing plugins really better?

I ask this genuinely - does it give a better experience of vagrant or does it make it even harder to use?

**Comment by cwonrails** [comment]
@ErisDS Just responded in Slack. I recommend creating a new branch dedicated to a 4.0 and merging @mike182uk's PRs into that branch, which will hopefully encourage more collaborators going forward.

@mike182uk Thanks again for your work here!

**Comment by mike182uk** [comment]
ok cool, no worries.

To answer the question, I would say it makes the experience better. For one, there is no need to manually edit / update your hosts file (as this is handled by `vagrant-hostsupdater`). `vagrant-librarian-puppet` is better for managing puppet dependencies than just plain old git submodules, which is probably not going to have a massive effect on the end user. `vagrant-cachier` is a good general purpose plugin to have and will save bandwidth on multiple provisions. It will also benefit any other VM's the user has. My change only adds 1 new step, and removes another, so there is still the same amount of steps.

**Comment by cwonrails** [comment]
I completely agree. Can a maintainer please merge this PR? It's been a long time and it works. cc @ErisDS

**Comment by sebgie** [comment]
Hi @mike182uk, @cwonrails, thanks for all your work here.

Big :+1: from me for getting rid of git submodules and using puppet modules instead.

Going forward I'll try to keep a closer eye on this repository and help to make the experience for using and contributing better :-).

**Pull request merged**
